SHOW TABLES;
SELECT COUNT(ID) FROM USER;
desc USER;
ALTER TABLE USER
	ADD COLUMN BIRTH DATE AFTER NAME;

ALTER TABLE 테이블이름
	ADD COLUMN 컬럼이름 타입 [AFTER 기존컬럼| FIRST];

ALTER TABLE 테이블이름
	DROP COLUMN 컬럼이름;

ALTER TABLE 테이블이름
	CHANGE COLUMN 컬럼이름 새이름 데이터타입 제약조건;

ALTER TABLE DEPT
	ADD CONSTRAINT DEPT_EMP_FK2
		FOREIGN KEY(LOCKER_ID)
		REFERENCES EMP(ID);
ALTER TABLE DEPT
	RENAME TO DEPARTMENT;
