USE NEXT_FIGHTER2;
LOAD DATA LOCAL INFILE 'ndata1.csv' INTO TABLE USER FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'ndata2.csv' INTO TABLE USER FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'ndata3.csv' INTO TABLE USER FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'ndata4.csv' INTO TABLE USER FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'ndata5.csv' INTO TABLE USER FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'ndata6.csv' INTO TABLE USER FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'ndata7.csv' INTO TABLE USER FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'ndata8.csv' INTO TABLE USER FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'ndata9.csv' INTO TABLE USER FIELDS TERMINATED BY ',';

SELECT COUNT(ID) FROM USER;
