USE NEXT_FIGHTER2;

DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
	ID CHAR(12) PRIMARY KEY,
	NAME VARCHAR(20),
	LEAGUE ENUM('D','P','G','S','B'),
	SCORE INT,
	LV TINYINT,
	NUM_PLAY INT,
	WIN INT
);

LOAD DATA LOCAL INFILE 'ndata0.csv' INTO TABLE USER FIELDS TERMINATED BY ',';
SELECT COUNT(*) FROM USER;
SELECT * FROM USER WHERE ID LIKE '%1' LIMIT 1;
